(()=>{'use strict';
const R=window.QY_RULES, $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const clamp=v=>Math.max(0,Math.min(1,Number(v)||0)), norm=s=>(s||'').toLowerCase().replace(/\s+/g,' ').trim();
const hits=(t,arr)=>arr.filter(x=>norm(t).includes(x.toLowerCase()));
const blank={cases:[],receipts:[],current:null,outcomes:[]};
let state=load();
function load(){try{return Object.assign(structuredClone(blank),JSON.parse(localStorage.getItem('qingyuan27')||'{}'))}catch(e){return structuredClone(blank)}}
function save(){try{localStorage.setItem('qingyuan27',JSON.stringify(state))}catch(e){} updateMetrics()}
function scoreText(text,purpose,cues=[]){
 let t=norm(text),a=hits(t,R.ABS),src=hits(t,R.SRC),corr=hits(t,R.CORR),m=hits(t,R.MAN),z=hits(t,R.ZERO),sales=hits(t,R.SALES),pseudo=hits(t,R.PSEUDO),vuln=hits(t+' '+norm($('#audience')?.value||''),R.VULN),prot=hits(t,R.PROT),parties=hits(t,R.PARTY);
 let evidence=clamp(.50+.08*src.length-.035*a.length-.07*pseudo.length); let careSlogan=/(照顾自己|爱自己|self-care|care for yourself)/.test(t)&&/(孩子|child|mother|妈妈|宝妈)/.test(t), careContext=/(协商|安全|暴力|资源|预算|替代照护|negotiate|safety|violence|resource|budget|substitute care)/.test(t); let context=clamp(.62+.07*corr.length+.04*Math.min(parties.length,3)-.06*a.length-.07*z.length-(sales.length&&!src.length?.10:0)-(careSlogan&&!careContext?.25:0));
 let manipulation=clamp(.06+.12*(m.length+z.length)), interest=clamp(.08+.11*sales.length+(sales.length&&!/(sponsored|affiliate|广告|赞助|佣金)/.test(t)?.18:0));
 let vulnerability=clamp(.04+.08*vuln.length+.09*m.length+(vuln.length&&sales.length?.12:0)), relational=clamp(.06+.12*z.length+(parties.length&&a.length?.05:0)+(/夫妻|spouse|partner/.test(t)?.10:0));
 let pseudoRisk=clamp(.08+.15*pseudo.length+.08*sales.length-.06*src.length-.04*corr.length), corrigibility=clamp(.42+.10*corr.length+.05*src.length-.06*a.length-.05*m.length), addiction=.04;
 cues.forEach(c=>addiction+=R.cueWeight[c]||.08); addiction=clamp(addiction);
 let protectedPurposes=['criticism','whistleblowing','grief','distress','news','audit','research'];
 let protectedExpression=(protectedPurposes.includes(purpose)||prot.length>0)&&manipulation<.45&&pseudoRisk<.45;
 let candidates=[],actions=[];
 if(protectedExpression){candidates.push([0,'PROTECTED_NEGATIVE_OR_CRITICAL_EXPRESSION']);actions.push('L0_PROTECT_EXPRESSION','PRESERVE_SOURCE_AND_CONTEXT')}
 if(evidence<.48){candidates.push([1,'EVIDENCE_NEEDED']);actions.push('L1_EVIDENCE_LABEL','ASK_FOR_SOURCE_AND_FALSIFIER')}
 if(context<.58){candidates.push([2,'CONTEXT_REPAIR_REQUIRED']);actions.push('L2_CONTEXT_COMPLETION_OVERLAY','SHOW_OMITTED_PARTIES_AND_EXCEPTIONS')}
 if(manipulation>=.42){candidates.push([3,'MANIPULATION_FRICTION_REQUIRED']);actions.push('L3_SHARE_FRICTION','COOLING_OFF_AND_IDENTITY_PRESSURE_WARNING')}
 if(addiction>=.38){candidates.push([4,'ADDICTION_CIRCUIT_BREAKER']);actions.push('L4_PAUSE_AUTOPLAY_AND_INFINITE_SCROLL','USER_CONTROLLED_SESSION_BREAK')}
 if(pseudoRisk>=.48||(interest>=.52&&evidence<.55)){candidates.push([5,'PSEUDO_KNOWLEDGE_COMMERCIAL_HOLD']);actions.push('L5_HOLD_PURCHASE_OR_SHARE','DISCLOSE_PRICE_REFUND_UPSELL_EVIDENCE')}
 if(vulnerability>=.48){candidates.push([5,'VULNERABLE_TARGET_PROTECTION']);actions.push('L5_REMOVE_PERSONALISED_PRESSURE','REQUIRE_PLAIN_LANGUAGE_AND_INDEPENDENT_REVIEW')}
 if(relational>=.48){candidates.push([4,'RELATIONAL_ZERO_SUM_REPAIR']);actions.push('RELATIONAL_BURDEN_MAP','REVERSIBLE_TRIAL_AND_REVIEW_DATE')}
 if(!candidates.length){candidates=[[0,'PASS_WITH_TRACEABLE_CONTEXT']];actions.push('L0_ALLOW','OPTIONAL_CONTEXT_CARD')}
 candidates.sort((x,y)=>y[0]-x[0]);
 let worlds=[
  {name:'truthful_but_uncomfortable',support:clamp(.16+.36*evidence+.22*(1-manipulation)+(protectedExpression?.18:0)-.10*pseudoRisk),test:'独立来源是否确认核心事实'},
  {name:'sincere_but_context_incomplete',support:clamp(.18+.35*(1-context)+.12*corrigibility-.10*manipulation),test:'被要求补条件时是否愿意补全'},
  {name:'commercial_persuasion',support:clamp(.10+.38*interest+.08*Math.min(sales.length,3)),test:'是否完整披露价格、退款、利益和独立结果'},
  {name:'manipulative_or_addictive_mechanism',support:clamp(.12+.30*manipulation+.20*pseudoRisk+.15*interest+.12*vulnerability),test:'移除压力线索后是否失去主要转化能力'},
  {name:'distress_or_help_signal',support:clamp(.08+((purpose==='distress')?.35:0)+.12*prot.length),test:'表达者是否寻求支持而非强迫他人'}
 ];
 return {version:'27.0.0',text,purpose,audience:$('#audience')?.value||'general',protected_expression:protectedExpression,primary_class:candidates[0][1],scores:{evidence_integrity:evidence,context_completeness:context,manipulation_pressure:manipulation,addiction_pressure:addiction,interest_opacity:interest,vulnerability_exploitation:vulnerability,relational_externality:relational,pseudo_knowledge_risk:pseudoRisk,corrigibility},worlds,interventions:[...new Set(actions)],signals:{a,src,corr,m,z,sales,pseudo,vuln,prot},automatic_external_action_authority:0,claim_boundary:'Heuristic research output; not a diagnosis, legal finding, person-level moral label or authority for automatic external action.'};
}
const dimNames={evidence_integrity:'证据完整',context_completeness:'语境完整',manipulation_pressure:'操纵压力',addiction_pressure:'成瘾压力',interest_opacity:'利益不透明',vulnerability_exploitation:'脆弱性利用',relational_externality:'关系外部性',pseudo_knowledge_risk:'伪知识风险',corrigibility:'可纠正性'};
function labelClass(c){return {'PROTECTED_NEGATIVE_OR_CRITICAL_EXPRESSION':'受保护的负面、批评或求助表达','EVIDENCE_NEEDED':'需要证据标记','CONTEXT_REPAIR_REQUIRED':'需要补全语境','MANIPULATION_FRICTION_REQUIRED':'需要主动增加摩擦','ADDICTION_CIRCUIT_BREAKER':'需要中断成瘾回路','PSEUDO_KNOWLEDGE_COMMERCIAL_HOLD':'应暂停购买或传播','VULNERABLE_TARGET_PROTECTION':'需要脆弱受众保护','RELATIONAL_ZERO_SUM_REPAIR':'需要修复零和关系漂移','PASS_WITH_TRACEABLE_CONTEXT':'可通过并保留语境'}[c]||c}
async function digest(s){let b=await crypto.subtle.digest('SHA-256',new TextEncoder().encode(s));return [...new Uint8Array(b)].map(x=>x.toString(16).padStart(2,'0')).join('')}
async function receipt(type,payload){let prev=state.receipts.length?state.receipts.at(-1).hash:'0'.repeat(64);let body={timestamp:new Date().toISOString(),event_type:type,payload,previous_hash:prev};body.hash=await digest(JSON.stringify(body));state.receipts.push(body);save();renderReceipts();return body}
function cues(){return $$('#cueChecks input:checked').map(x=>x.value)}
function renderAnalysis(r){state.current=r;$('#primaryDecision').textContent=labelClass(r.primary_class);$('#primaryDecision').className='decision '+((r.primary_class.includes('HOLD')||r.primary_class.includes('VULNERABLE'))?'danger':(r.primary_class.includes('FRICTION')||r.primary_class.includes('CONTEXT')||r.primary_class.includes('ADDICTION'))?'warn':'');$('#protectedFlag').innerHTML=r.protected_expression?'<div class="callout"><b>Protected expression:</b> 不因负面情绪、批评、举报或坏消息而压制。</div>':'';
 $('#scoreGrid').innerHTML=Object.entries(r.scores).map(([k,v])=>`<div class="score"><div class="row"><span>${dimNames[k]||k}</span><b>${Math.round(v*100)}</b></div><div class="bar"><span style="width:${Math.round(v*100)}%"></span></div></div>`).join('');
 $('#worlds').innerHTML=r.worlds.sort((a,b)=>b.support-a.support).map(w=>`<div class="world"><b><span>${w.name}</span><span>${Math.round(w.support*100)}%</span></b><small>区分观察：${w.test}</small></div>`).join('');
 $('#interventions').innerHTML=r.interventions.map(x=>`<span class="chip">${x}</span>`).join('');renderPlan();updateMetrics();save();}
async function runAnalysis(){let text=$('#contentText').value.trim();if(!text){alert('请先输入内容。');return}let r=scoreText(text,$('#purpose').value,cues());state.cases.push({at:new Date().toISOString(),result:r});renderAnalysis(r);await receipt('content_analysis',{primary:r.primary_class,protected:r.protected_expression,scores:r.scores,text_digest:await digest(text)});}
function contextRepair(){let t=norm($('#contentText').value),family=(/(照顾自己|爱自己|self-care|care for yourself)/.test(t)&&/(孩子|child|mother|妈妈|宝妈)/.test(t));let missing=family?['孩子的安全与发展需要','伴侣与家庭劳动的真实分配','时间、收入与替代照护资源','暴力、强迫控制、严重健康风险例外','可执行的协商、试行和复盘日期']:['谁受到影响、谁承担负担','适用范围、条件与例外','来源与证据层级','利益冲突与销售动机','如何更正、证伪与复盘'];let repaired=family?'照护者的休息、健康与安全是家庭共同责任，但自我照顾不应被解释为把孩子的基本照护、风险或全部家务单边转移给另一方。应先明确孩子的安全与发展需要，再由伴侣、家庭成员或社会支持共同协商时间、劳动、预算和替代照护；若存在暴力、强迫控制、严重抑郁、单亲无支持或紧急健康风险，应优先寻求专业与公共支持，而不是用一句口号处理复杂处境。':'将断言改写为条件命题：明确受益者、受影响主体、证据、例外、负担分配、利益关系和复盘节点。';$('#contextMissing').innerHTML='<h3>遗漏语境</h3><ul>'+missing.map(x=>`<li>${x}</li>`).join('')+'</ul>';$('#contextRepair').textContent=repaired;$('#contextRisk').innerHTML='<p><b>风险：</b>局部合理原则若被绝对化，可能变成身份战争、单边负担转移或销售钩子。</p>';receipt('context_repair',{family_case:family,missing,repaired});}
function relation(){let g=id=>Number($('#'+id).value)/100,violence=$('#relViolence').checked;if(violence){$('#relationDecision').textContent='SAFETY_FIRST_EXCEPTION';$('#relationText').textContent='存在暴力或强迫控制时，优先安全、专业支持和受保护决策；一般妥协不是首要干预。';$('#relationMeter').style.width='0%';return}let d=clamp(.38*g('relBurden')+.30*g('relContempt')+.22*g('relDependent')-.18*g('relNegotiation')-.12*g('relSupport')+.18);let mode=d>=.62?'HIGH_ZERO_SUM_DRIFT':d>=.35?'REPAIRABLE_TENSION':'COOPERATIVE_RANGE';$('#relationDecision').textContent=mode+' · '+Math.round(d*100);$('#relationDecision').className='decision '+(d>=.62?'danger':d>=.35?'warn':'');$('#relationMeter').style.width=Math.round(d*100)+'%';$('#relationText').textContent='建议显式列出孩子与照护者需要、双方劳动、收入、休息、替代资源和复盘日期；先做可撤销的小范围试行。';receipt('relationship_simulation',{mode,zero_sum_drift:d});}
function offerAudit(){let t=norm($('#offerText').value),sales=hits(t,R.SALES),pseudo=hits(t,R.PSEUDO),src=hits(t,R.SRC),corr=hits(t,R.CORR),price=Number($('#offerPrice').value)||0,refund=$('#offerRefund').value,cred=$('#offerCredentials').value,links=Number($('#offerLinks').value)||0;let opacity=.18+.10*sales.length+(price&&!refund?.20:0)+(price&&!cred?.12:0),gap=.55+.12*pseudo.length-.10*src.length-.06*links-.06*corr.length,risk=clamp(.45*opacity+.55*gap),decision=risk>=.55?'PSEUDO_KNOWLEDGE_COMMERCIAL_HOLD':'ALLOW_WITH_DISCLOSURE_AND_EVIDENCE';$('#offerDecision').textContent=decision+' · '+Math.round(risk*100);$('#offerDecision').className='decision '+(risk>=.55?'danger':'');$('#offerDetails').innerHTML=`<p>销售线索：${sales.join('、')||'无'}<br>伪知识线索：${pseudo.join('、')||'无'}<br>来源线索：${src.join('、')||'无'}</p>`;receipt('knowledge_offer_audit',{risk,decision,price,sales,pseudo,source_count:src.length});}
function addiction(){let min=Number($('#dailyMinutes').value)||0,night=Number($('#nightInterruptions').value)||0,open=Number($('#unplannedOpens').value)||0,dist=Number($('#postDistress').value)||0;let risk=clamp(min/480*.35+night/8*.22+open/30*.20+dist/100*.23);$('#addictionRisk').textContent=(risk>=.65?'HIGH CIRCUIT RISK':risk>=.38?'MODERATE CIRCUIT RISK':'LOWER CIRCUIT RISK')+' · '+Math.round(risk*100);$('#addictionRisk').className='decision '+(risk>=.65?'danger':risk>=.38?'warn':'');let plan=[`关闭自动播放和非必要推送至少7天`,`把应用移出主屏并在打开前写下目的`,`每${risk>=.65?20:35}分钟强制离屏休息`,`睡前90分钟禁用推荐流`,`隐藏点赞、连胜和随机奖励线索`,`记录使用前后情绪，7天后根据现实结果调整`];$('#addictionPlan').innerHTML='<ol>'+plan.map(x=>`<li>${x}</li>`).join('')+'</ol>';receipt('addiction_plan',{risk,plan});}
function evidenceMatrix(){let text=$('#contentText').value||'',parts=text.split(/[。！？.!?\n]+/).map(x=>x.trim()).filter(Boolean).slice(0,8);if(!parts.length)parts=['尚未输入主张'];$('#evidenceBody').innerHTML=parts.map(p=>{let type=/(应该|必须|should|must)/i.test(p)?'行动建议':/(可能|推测|may|might)/i.test(p)?'推断/假设':/(我觉得|我感到|I feel)/i.test(p)?'体验陈述':'事实性主张';let ev=hits(p,R.SRC).length?'存在来源线索':'未见来源';return `<tr><td>${esc(p)}</td><td>${type}</td><td>${ev}</td><td>不能单独证明普遍因果、适用于所有人或无例外</td><td>原始记录、独立来源、反例和受影响者结果</td></tr>`}).join('');receipt('evidence_matrix',{claims:parts.length});}
function share(){if(!state.current){$('#shareDecision').textContent='先完成内容体检。';return}let s=state.current.scores,hold=s.manipulation_pressure>=.42||s.pseudo_knowledge_risk>=.48||s.context_completeness<.5||s.addiction_pressure>=.5;let label=hold?'PAUSE — 先补证据、语境或冷却后再决定':'SHARE WITH CONTEXT — 可分享但保留来源、边界和纠错';$('#shareDecision').textContent=label;$('#shareDecision').className='decision '+(hold?'danger':'');$('#shareReason').textContent=hold?'当前存在操纵、伪知识、语境截断或成瘾放大风险。':'未发现需要暂停的强信号，但仍应保留来源与纠错。';receipt('share_gate',{decision:label});}
function renderPlan(){let levels=[['L0','保护与保留'],['L1','证据标记'],['L2','补全语境'],['L3','分享摩擦'],['L4','用户降放大'],['L5','本地隔离/商业暂停'],['L6','正当程序修复']];let actions=state.current?.interventions||[];let active=state.current?.primary_class||'';let idx=active.includes('VERIFIED')?6:active.includes('HOLD')||active.includes('VULNERABLE')?5:active.includes('ADDICTION')||active.includes('RELATIONAL')?4:active.includes('MANIPULATION')?3:active.includes('CONTEXT')?2:active.includes('EVIDENCE')?1:0;$('#ladder').innerHTML=levels.map((x,i)=>`<div class="rung ${i===idx?'active':''}"><strong>${x[0]}</strong><b>${x[1]}</b><p>${['不压制真实坏消息和求助','标明不确定与来源','显示遗漏主体和例外','冷却、确认、减少冲动转发','暂停自动播放、滚动和随机奖励','高风险内容由用户隔离；售卖需补披露','更正触达、申诉、返还和机制修复'][i]}</p></div>`).join('');$('#planOutput').innerHTML=actions.length?'<div class="chips">'+actions.map(x=>`<span class="chip">${x}</span>`).join('')+'</div>':'<p>先完成内容体检。</p>'}
async function outcome(){let text=$('#outcomeText').value.trim(),severity=Number($('#outcomeSeverity').value)/100,evidence=$('#outcomeEvidence').value;if(!text){alert('请描述现实结果。');return}let action=severity>=.65?'STOP_AMPLIFICATION_AND_OPEN_REPAIR':severity>=.35?'CORRECT_AND_MONITOR':'RECORD_AND_REVIEW';let rec=await receipt('reality_outcome',{text,severity,evidence,action});state.outcomes.push(rec);save();$('#outcomeReceipt').innerHTML=`<div class="decision ${severity>=.65?'danger':severity>=.35?'warn':''}">${action}</div><p>回执：${rec.hash.slice(0,20)}…</p>`}
async function verifyReceipts(){let prev='0'.repeat(64),valid=true;for(const r of state.receipts){if(r.previous_hash!==prev){valid=false;break}let body={timestamp:r.timestamp,event_type:r.event_type,payload:r.payload,previous_hash:r.previous_hash};if(await digest(JSON.stringify(body))!==r.hash){valid=false;break}prev=r.hash}$('#receiptStatus').innerHTML=`<div class="decision ${valid?'':'danger'}">${valid?'VALID':'INVALID'} · ${state.receipts.length} records</div>`}
function renderReceipts(){$('#receiptList').textContent=state.receipts.slice(-20).map(r=>`${r.timestamp}  ${r.event_type}\n${r.hash}`).join('\n\n')||'暂无回执。'}
function updateMetrics(){$('#metricCases').textContent=state.cases.length;$('#metricProtected').textContent=state.cases.filter(x=>x.result?.protected_expression).length;$('#metricFriction').textContent=state.cases.filter(x=>/FRICTION|HOLD|ADDICTION|RELATIONAL|VULNERABLE/.test(x.result?.primary_class||'')).length;$('#metricReceipts').textContent=state.receipts.length}
function exportAll(){let payload={package_version:'27.0.0',exported_at:new Date().toISOString(),case:state.current?{text:state.current.text,purpose:state.current.purpose}:null,analysis:state.current,intervention_plan:{actions:state.current?.interventions||[],external_automatic_action_authority:0},receipts:state.receipts,outcomes:state.outcomes,hard_invariants:{human_worth_ranking:0,political_viewpoint_penalty:0,negative_emotion_suppression:0,external_automatic_action:0}};let txt=JSON.stringify(payload,null,2);$('#exportPreview').value=txt;let a=document.createElement('a');a.href=URL.createObjectURL(new Blob([txt],{type:'application/json'}));a.download='qingyuan27-cognitive-immunity-package.cipkg.json';a.click();URL.revokeObjectURL(a.href)}
function esc(s){return String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function bind(){
 $$('#nav button').forEach(b=>b.onclick=()=>{$$('#nav button').forEach(x=>x.classList.remove('active'));b.classList.add('active');$$('.view').forEach(v=>v.classList.remove('active'));$('#'+b.dataset.view).classList.add('active');$('#pageTitle').textContent=b.textContent;window.scrollTo({top:0,behavior:'smooth'})});
 $$('input[type=range]').forEach(x=>x.oninput=()=>x.nextElementSibling&&(x.nextElementSibling.value=x.value));
 $('#loadExample').onclick=()=>{$('#contentText').value='女性要先好好照顾自己才能照顾孩子。真正觉醒的女人不能向家庭妥协，马上加入训练营。';$('#purpose').value='education';$('#audience').value='caregivers';$$('#cueChecks input').forEach(x=>x.checked=['autoplay','infinite_scroll','outrage_loop'].includes(x.value))};
 $('#analyzeBtn').onclick=runAnalysis;$('#clearBtn').onclick=()=>{$('#contentText').value='';state.current=null;save()};$('#contextBtn').onclick=contextRepair;$('#relationBtn').onclick=relation;$('#offerBtn').onclick=offerAudit;$('#addictionBtn').onclick=addiction;$('#evidenceBtn').onclick=evidenceMatrix;$('#shareBtn').onclick=share;$('#outcomeBtn').onclick=outcome;$('#verifyReceipts').onclick=verifyReceipts;$('#clearReceipts').onclick=()=>{if(confirm('清除全部本地回执？')){state.receipts=[];save();renderReceipts()}};$('#exportBtn').onclick=exportAll;$('#importBtn').onclick=()=>$('#importFile').click();$('#importFile').onchange=e=>{let f=e.target.files[0];if(!f)return;let r=new FileReader();r.onload=()=>{try{let x=JSON.parse(r.result);state=Object.assign(structuredClone(blank),x.state||x);save();location.reload()}catch(err){alert('JSON无效')}};r.readAsText(f)};$('#resetBtn').onclick=()=>{if(confirm('清除全部本地数据？')){localStorage.removeItem('qingyuan27');state=structuredClone(blank);location.reload()}};
 }
 bind();updateMetrics();renderReceipts();renderPlan();if(state.current)renderAnalysis(state.current);
})();
